### ISSUE TITLE
Postgres Port on restore 5433

### ISSUE THREAD

**Issue by VitalJeevanjot** [hollaex/hollaex-cli#227]
Greetings,

I would like to point out that here https://github.com/bitholla/hollaex-cli/blob/master/hollaex#L6766 the port is different from `settings/secret`/original Postgres port which is `5432`, refusing to connect to postgresdb.

Regards,

**Comment by kycfeel** [comment]
Hey there.

Sorry for replying to you so late. 

The port 5433 will be only used for running the HollaEx Network server with the CLI, not for the Kit itself.

For the Kit DB backup/restore, port 5432 will be used.

You could ignore that part.

Thank you so much for your attention to the project.
